### ISSUE TITLE
Choose directory for image download

### ISSUE THREAD

**Issue by samueldamon** [rconradharris/reddit-background#14]
In the latest version of reddit-background, the program automatically downloads images to the "Reddit Backgrounds" as opposed to the previous hidden folder. Is there any way to download images to a specific folder, and if not, would it be possible to add this feature?

Thanks!

**Comment by rconradharris** [comment]
@sbd01 Yep, you can use either `--download-directory` on the command-line or use `download_directory` in your config file to override the default.
