### ISSUE TITLE
[Documentation] Provide examples for multiple subreddits

### ISSUE THREAD

**Issue by Macxim** [rconradharris/reddit-background#20]
For example here: https://github.com/rconradharris/reddit-background/blob/master/examples/set_background.conf#L13

Could you provide an example for multiple subreddits, like 2 or 3?
Should they be separated by commas (`,`), spaces (` `), pipes (`|`)?

Thank you very much.

**Comment by rconradharris** [comment]
@Macxim You can use commas to add additional entries (https://github.com/rconradharris/reddit-background/blob/master/reddit-background#L630)

Thanks for bringing up the lack of documentation on this, definitely should include an example.

**Comment by Macxim** [comment]
Indeed I had spotted that line myself but I meant to make it clearer for everyone.
Cool project 👍 Thanks!
