### ISSUE TITLE
Many duplicates?

### ISSUE THREAD

**Issue by eddyerburgh** [rconradharris/reddit-background#21]
Hi, I've set a cron job to run every 15mins:

```
reddit-background EarthPorn:top:1000:week
```

I'd expect to see a lot more variety than I'm getting. It seems to rotate through 3-4 pictures a day. 

Is there a better way to rotate through a lot of pictures with high upvotes?

**Comment by Macxim** [comment]
I notice the same thing on my machine.

**Comment by rconradharris** [comment]
The `-vv` option will display the ranking table to give you an idea why it's choosing the images it's choosing.

It's possible that the `jitter` score (what adds randomness) isn't weighted heavily enough, so it's stuck picking the same few images.

Maybe there's a better approach here. Perhaps having a cutoff where you can say, 'pick a random image from the top X images', where X is configurable.

The default might be 10. In that case we could remove jitter entirely.

For those that want even more variety, they could bump that X (`top_images_cutoff`) to something like 20.  Bumping it to 100 makes the algorithm completely random. Thoughts?

**Comment by Macxim** [comment]
Sounds good to me.

**Comment by rconradharris** [comment]
Decided to make the 'image choosers' pluggable. Now we have two: the existing 'bestmatch' chooser, and a new 'random' chooser.

'bestmatch' remains the default, but you can configure it to use random by using 'image_chooser=random' in the config file.
