### ISSUE TITLE
Images not being displayed at all

### ISSUE THREAD

**Issue by NickGaens** [rconradharris/reddit-background#23]
I've successfully followed your installation guide but it seems your program fails to set my display backgrounds. The default Sierra image remains visible.

Here's my ~/.reddit-background.conf:
```
[default]

# Symlink will show filename/title on desktop
desktop_symlink = True

# Use the 'bestmatch' image chooser
image_chooser = bestmatch

# Download number of images per desktop
image_count = 10

[desktop1]
subreddits=CarPorn:top:25:week,CityPorn:top:25:week,EarthPorn:top:25:week,SpacePorn:top:25:week

[desktop2]
subreddits=CarPorn:top:25:week,CityPorn:top:25:week,EarthPorn:top:25:week,SpacePorn:top:25:week

[desktop3]
subreddits={seasonal}
```

-> I added /usr/local/bin/reddit-background/reddit-background to launchd using the app LaunchControl, but no background images were being set.
-> Running the reddit-background binary from Terminal (`sudo ./reddit-background {seasonal}`) does not change the background images either.

I'm running macOS Sierra 10.12.4 on a 15" MBPr Mid 2015 with two external displays attached to it.

**Comment by rconradharris** [comment]
@NickGaens With `image_count = 10` set, reddit-background will only download the images, not set the background itself. Do you have the Mac desktop chooser pointed at the `~/Reddit Backgrounds` directory? If not, then no backgrounds will be selected.

The other option is to have `reddit-background` set the background for you. You can do this by setting `image_count=0`.

**Comment by NickGaens** [comment]
Oh, I understand. I've set it to `image_count = 0`.

As it turns out, I'm now running into a different issue (permission related), so I'm closing this one and will open a new one.
