### ISSUE TITLE
Cache only mode

### ISSUE THREAD

**Issue by rconradharris** [rconradharris/reddit-background#3]
@awendland had the good idea of a cache-only mode that can be then used to integrate with the default Mac OS X desktop background-picker.

To handle this we would need:

`--cache-only` CLI option
`cache_only` config-file option
default=False

When cache_only mode is used, we'll download the images to our folder but won't actually set the desktop background (we'll let OS X do that for us).

It'd probably be nice to specify the download directory as well, so we'd also want:

`--download-directory` CLI option
`download_directory` config-file option
default = ~/.background-images

**Comment by awendland** [comment]
Minor note: the default directory should not be a dotfile because the OSX
desktop background selector does not allow hidden folders to be selected.

**Comment by rconradharris** [comment]
@awendland Ah good call.

Also, thinking `--cache-only` is a little too techy... maybe `--download-only` will make more sense to non-programmers.

**Comment by awendland** [comment]
Haha, I wouldn't be too concerned. The program is downloaded by running
git-clone and is automated through crontab or run from the command line.
It's already made for people of relatively high tech understanding.

Even though, "download" does describe the feature better. The caching that
I discussed was not really caching, more of downloading and refraining from
redownloading each time.
